### ISSUE TITLE
Update README to clarify module release history

### ISSUE THREAD

**Issue by mbrukman** [OpenTSDB/asyncbigtable#23]
The [`README` currently says](https://github.com/OpenTSDB/asyncbigtable/commit/6126a8e409fab7da75a6314a2aab1e2c2b03d774):

> Changelog
> ---
> This project uses Semantic Versioning.
> 
> ### 0.3.0
>
> [...]
>
> ### 0.2.1
>
> [...]

However, it doesn't appear that v0.2.1 was ever released or published. If we [search on Maven Central](https://search.maven.org/#search%7Cga%7C1%7Ccom.pythian.opentsdb), the only version of `com.pythian.opentsdb` that appears is v0.1.0, there's no mention of v0.2.1 .

So, is the "0.2.1" heading here supposed to be changed to 0.1.0 instead? Or was there a release of 0.2.1 somewhere that's not obvious?

I believe 0.2.1 was at some point added to `pom.xml` as a version, it might have not just been built and released, so perhaps there was another 0.1.0 release prior to that?

On the other hand, OpenTSDB depends on [`asyncbigtable` 0.2.1-20160228.235952-3](https://github.com/OpenTSDB/opentsdb/blob/cac608ad7bfaf6315fd2319a8af37da307abdeb9/third_party/asyncbigtable/include.mk#L16), but that version isn't listed as a [version of `com.pythian.opentsdb/asyncbigtable`](http://mavenrepository.com/artifact/com.pythian.opentsdb/asyncbigtable), so it's confusing as to where it comes from.

Would be nice to clarify the history of this module for clarity:

- [ ] add v0.1.0 with features, date of release, etc.
- [x] clarify where v0.2.x was released and how

@csoulios, I'm guessing you're the expert on the history of this module, so would be great to get an authoritative record from you.

**Comment by csoulios** [comment]
You are right @mbrukman and thanks for spotting this. Version 0.2 was always a SNAPSHOT and was never released properly.

Today I released version 0.3.0 (see https://oss.sonatype.org/content/repositories/releases/com/pythian/opentsdb/asyncbigtable/0.3.0/)

Since the upgrade of the bigtable-client dependency was a major change, I decided to bump up the asyncbigtable version to 0.3.0

I will fix the documentation and make sure to clarify history.

**Comment by csoulios** [comment]
Released version v0.2.1 for historical reasons, since this is the one (its SNAPSHOT) used by OpenTSDB 2.3

https://github.com/OpenTSDB/asyncbigtable/tree/v0.2.1
https://oss.sonatype.org/content/repositories/releases/com/pythian/opentsdb/asyncbigtable/0.2.1/
