### ISSUE TITLE
Update version of Bigtable client library from 0.9.6

### ISSUE THREAD

**Issue by mbrukman** [OpenTSDB/asyncbigtable#24]
The [current Bigtable dependencies in `pom.xml`](https://github.com/OpenTSDB/asyncbigtable/blob/bdac2d2c35956e0283de8181fe5b161fe7b035ba/pom.xml#L221-L231) are as follows:

```xml
<dependency>
  <groupId>com.google.cloud.bigtable</groupId>
  <artifactId>bigtable-hbase-1.2</artifactId>
  <version>0.9.6</version>
</dependency>

<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-tcnative-boringssl-static</artifactId>
  <version>1.1.33.Fork26</version>
</dependency>
```

This should be updated to either 0.9.7.x series or straight to 1.0.0 series (current latest version is 1.0.0-pre2; we can upgrade now or wait until 1.0.0 final is released).

@sduskis, @igorbernstein — what do you think?

**Comment by igorbernstein** [comment]
I don't think upgrading to 0.9.7.x makes sense. I would recommend to update to bigtable-hbase-1.x-hadoop 1.0.0-pre2 now and then updating to 1.0.0 final when it's ready

**Comment by manolama** [comment]
Bumped to 1.0.0-pre2 in 8123a671144e117b48d3d905c1b9eddf97f78048 thanks!
