### ISSUE TITLE
PutRequest without calling flush() on the client

### ISSUE THREAD

**Issue by vankofalcon** [OpenTSDB/asyncbigtable#42]
Hey guys,
maybe I'm missing something but I can't create a single PutRequest without calling flush on the client before that. If I don't call flush, the put request is blocked and never finishes.

`Deferred<Object> result = client.put(new PutRequest(...));
result.join()`

If I do only this, the call never finishes. So should I call flush to batch myself?

**Comment by sduskis** [comment]
Are you looking for a Bigtable asyc API?  If so, I would highly suggest using the Cloud Bigtable HBase 2 async API.

Asyncbigtable is optimized to work with OpenTSDB, and gives very few options on how to manage async operations.

**Comment by vankofalcon** [comment]
I'm already using the asynchbase library against hbase and I'm trying to make it work on bigtable without making lot's of code changes.
Cloud Bigtable HBase 2 async API? That's looks interesting. Can you please point me to some examples?

**Comment by sduskis** [comment]
[Here's the AsyncTable javadocs](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/AsyncTable.html).  

From a maven perspective, you'd have to add the following artifact (which by the way requires Java 8):

```xml
 <dependency>
     <groupId>com.google.cloud.bigtable</groupId>
     <artifactId>bigtable-hbase-2.x</artifactId>
     <version>1.3.0</version>
 </dependency>
```

[Here's how it's used](https://github.com/OpenTSDB/asyncbigtable/blob/master/src/main/java/org/hbase/async/HBaseClient.java#L289) in the latest incarnation of asyncBigtable's HBaseClient.

```java
 Configuration conf = BigtableConfiguration.asyncConfigure(...);
 AsyncConnection conn = ConnectionFactory.createAsyncConnection(conf).get();
 AsyncTable<...> table = conn.getTable(...);
 CompletableFuture cf = table.put(...);
```

We didn't document this feature yet, but we will once we do a bit more work to upgrade from HBase 2.0.0-beta2 to the recently released HBase 2.0.0.

**Comment by sduskis** [comment]
AsyncBigtable was written with the assumption of a constant stream of `Put`s like those in timeseries databases.  We optimize for overall throughput using HBase's [BufferedMutator](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/BufferedMutator.html). 

AsyncBIgtable is not owned by the Cloud Bigtable team, so we have some trouble supporting it.  The HBase 2.0 API is owned by the CBT team, and is fully supported by the CBT team.

**Comment by sduskis** [comment]
So... back to the original question.  You either need to `flush()` or wait for a timer to complete.  The implementation won't work well at scale well if you `flush()` across many threads.  `flush()` is going to do some locking, so you won't be able to perform parallel `Put`s effectively.

**Comment by vankofalcon** [comment]
Thanks for the replies.
