### ISSUE TITLE
Snapshot release

### ISSUE THREAD

**Issue by overthetop** [OpenTSDB/asyncbigtable#45]
Can somebody please release the snapshot here https://oss.sonatype.org/content/repositories/snapshots?

**Comment by overthetop** [comment]
I can't do it myself 
`[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy (injected-nexus-deploy) on project asyncbigtable: Failed to deploy artifacts: Could not transfer artifact com.pythian.opentsdb:asyncbigtable:jar:0.3.1-20180611.152103-3 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/pythian/opentsdb/asyncbigtable/0.3.1-SNAPSHOT/asyncbigtable-0.3.1-20180611.152103-3.jar. Return code is: 401, ReasonPhrase: Unauthorized.`

**Comment by overthetop** [comment]
The last snapshot release that have been done there was last year, I hope that we can keep that repo active

https://oss.sonatype.org/content/repositories/snapshots/com/pythian/opentsdb/asyncbigtable/0.3.1-SNAPSHOT/

**Comment by csoulios** [comment]
@overthetop just released a 0.3.1-SNAPSHOT release. Please check
https://oss.sonatype.org/content/repositories/snapshots/com/pythian/opentsdb/asyncbigtable/0.3.1-SNAPSHOT/

**Comment by overthetop** [comment]
Thanks @csoulios. Do you think that we can make the snapshot releases automatic on master with travis ci?

**Comment by sduskis** [comment]
I don't think asyncbigtable needs to automate snapshots, since the updates are few and far between.

**Comment by sduskis** [comment]
There was a new full release of asyncbigtable.
